site_name: SQL Case Studies

theme:
  name: material
  features:
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      execute: false
      include_requirejs: true
      custom_mathjax_url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe"

nav:
  - Setup: index.md
  - Entity Relationship Diagrams: erd.md
  - Python API Reference:
      - Athena Client: athena_client.md
      - Utils: utils.md
  - Balanced Tree: balanced_tree.ipynb
  - Bitcoin:
      - EDA: bitcoin_eda.ipynb
      - Window Functions: bitcoin_window_functions.ipynb
  - Clique Bait: clique_bait.ipynb
  - Danny's Diner: dannys_diner.ipynb
  - Data Bank: data_bank.ipynb
  - Data Mart: data_mart.ipynb
  - Foodie Fi: foodie_fi.ipynb
  - Fresh Segments: fresh_segments.ipynb
